#!/bin/bash
# Bootstrap the /dev skill into ~/.claude/skills/dev/
# Run this on the host or in any new container:
#   bash bootstrap_dev_skill.sh
set -e
SKILL_DIR="$HOME/.claude/skills/dev"
mkdir -p "$SKILL_DIR"

echo "Installing /dev skill to $SKILL_DIR..."

# SKILL.md
cat > "$SKILL_DIR/SKILL.md" << 'SKILLEOF'
---
name: dev
description: Start a development task using the 4-phase workflow (RFC → TODO → Human approval → TDD execution). Automatically loads relevant corpus context. Use for any Frappe or general development task.
arguments: [task]
---

You are starting a development task. Follow the 4-phase workflow strictly.

## Step 1 — Load Corpus Context

Run the following to find and search the corpus:

```bash
# Auto-generate corpus if missing
if [ ! -f corpus.jsonl ]; then
  echo "corpus.jsonl not found — generating..."
  python3 generate_corpus.py 2>/dev/null || echo "No generate_corpus.py found, skipping."
fi

# Search for relevant context
python3 search_corpus.py "$task" --top 20 2>/dev/null || echo "No search_corpus.py found."
```

Read the output carefully. These are the actual DocTypes, controllers, and APIs relevant to this task.

If no corpus tools exist, ask the user: "Should I generate a corpus.jsonl for this project first?"

## Step 2 — Phase 1: RFC (Discuss Only)

Using the corpus context above, produce a Markdown RFC covering:
- What needs to be built and why
- Which existing DocTypes/APIs are involved (reference them by name from corpus output)
- Architectural boundaries — what should NOT change
- Open questions that need human input

**Rule: No code. No file creation. Discussion only.**

## Step 3 — Phase 2: Granular TODO

Transform the RFC into a hyper-specific TODO list. Every item must follow these rules:

- **TDD First**: test item comes before implementation item
- **Absolute paths**: every file referenced uses its full workspace path
- **Implementation block**: each item describes the expected logic in detail
- **bench run-tests command**: include the exact test command for each test item

Format:
```
- [ ] TEST: <what it verifies> — `bench run-tests --app <app> --doctype "<DocType>"`
      File: /full/path/to/test_file.py
      Logic: <what the test asserts>

- [ ] IMPL: <what to implement>
      File: /full/path/to/controller.py
      Logic: <exact implementation detail>
```

## Step 4 — Phase 3: Human Gatekeeping

Present the TODO list and explicitly ask:
> "Does this TODO match what you want? Any changes before I start executing?"

**Do not proceed to Phase 4 until the user approves.**

## Step 5 — Phase 4: Execute

Work through the TODO list one item at a time:
1. Scaffold with `bench` CLI if new DocType
2. Write the failing test — run it to confirm it fails
3. Implement until `bench run-tests` passes
4. Commit with a Conventional Commit message

After each file edit, the corpus auto-updates via the PostToolUse hook.

SKILLEOF

# generate_corpus.py
echo "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIKR2VuZXJhdGVzIGNvcnB1cy5qc29ubCBmcm9tIGN1c3RvbSBGcmFwcGUgYXBwcy4KRWFjaCBsaW5lIGlzIGEgc2VsZi1jb250YWluZWQgSlNPTiBvYmplY3QgZGVzY3JpYmluZyBhIERvY1R5cGUsIGNvbnRyb2xsZXIsIGhvb2ssIG9yIEFQSS4KClVzYWdlOgogICAgcHl0aG9uMyBnZW5lcmF0ZV9jb3JwdXMucHkKICAgIHB5dGhvbjMgZ2VuZXJhdGVfY29ycHVzLnB5IC0tYXBwcyBwMnBfZXNjcm93IHAycF9hZG1pbgogICAgcHl0aG9uMyBnZW5lcmF0ZV9jb3JwdXMucHkgLS1vdXRwdXQgbXlfY29ycHVzLmpzb25sCiIiIgoKaW1wb3J0IGFzdAppbXBvcnQganNvbgppbXBvcnQgYXJncGFyc2UKaW1wb3J0IG9zCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKZGVmIF9maW5kX2JlbmNoKCkgLT4gUGF0aDoKICAgICIiIldhbGsgdXAgZnJvbSBDV0QgdG8gZmluZCBhIEZyYXBwZSBiZW5jaCAoZGlyZWN0b3J5IGNvbnRhaW5pbmcgYXBwcy8gYW5kIHNpdGVzLykuIiIiCiAgICBjd2QgPSBQYXRoKG9zLmVudmlyb24uZ2V0KCJGUkFQUEVfQkVOQ0hfUEFUSCIsICIiKSkucmVzb2x2ZSgpIGlmIG9zLmVudmlyb24uZ2V0KCJGUkFQUEVfQkVOQ0hfUEFUSCIpIGVsc2UgTm9uZQogICAgaWYgY3dkIGFuZCAoY3dkIC8gImFwcHMiKS5leGlzdHMoKToKICAgICAgICByZXR1cm4gY3dkCiAgICBmb3IgcGF0aCBpbiBbUGF0aC5jd2QoKSwgKlBhdGguY3dkKCkucGFyZW50c106CiAgICAgICAgaWYgKHBhdGggLyAiYXBwcyIpLmV4aXN0cygpIGFuZCAocGF0aCAvICJzaXRlcyIpLmV4aXN0cygpOgogICAgICAgICAgICByZXR1cm4gcGF0aAogICAgIyBmYWxsYmFjawogICAgcmV0dXJuIFBhdGgoIi93b3Jrc3BhY2UvZGV2ZWxvcG1lbnQvY2Fub3BpLWJlbmNoIikKCkJFTkNIX1BBVEggPSBfZmluZF9iZW5jaCgpCkFQUFNfUEFUSCA9IEJFTkNIX1BBVEggLyAiYXBwcyIKCmRlZiBfZGVmYXVsdF9hcHBzKCkgLT4gbGlzdFtzdHJdOgogICAgIiIiUmV0dXJuIGFsbCBhcHBzIGluIHRoZSBiZW5jaCwgZXhjbHVkaW5nIGNvcmUgRnJhcHBlIGFwcHMuIiIiCiAgICBjb3JlID0geyJmcmFwcGUiLCAiZXJwbmV4dCIsICJocm1zIiwgInBheW1lbnRzIiwgImluc2lnaHRzIiwgImluZGlhX2NvbXBsaWFuY2UiLAogICAgICAgICAgICAibWljcm9zb2Z0X2ludGVncmF0aW9uIiwgImF0c2xfbWlncmF0b3IiLCAiZ3JpZXZhbmNlIiwgInRlY2hhZGVteV9lcnAifQogICAgaWYgbm90IEFQUFNfUEFUSC5leGlzdHMoKToKICAgICAgICByZXR1cm4gW10KICAgIHJldHVybiBbcC5uYW1lIGZvciBwIGluIHNvcnRlZChBUFBTX1BBVEguaXRlcmRpcigpKSBpZiBwLmlzX2RpcigpIGFuZCBwLm5hbWUgbm90IGluIGNvcmVdCgpDVVNUT01fQVBQUyA9IF9kZWZhdWx0X2FwcHMoKQoKCmRlZiBleHRyYWN0X2RvY3R5cGUoanNvbl9wYXRoOiBQYXRoKSAtPiBkaWN0IHwgTm9uZToKICAgIHRyeToKICAgICAgICBkYXRhID0ganNvbi5sb2Fkcyhqc29uX3BhdGgucmVhZF90ZXh0KCkpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHJldHVybiBOb25lCgogICAgZmllbGRzID0gWwogICAgICAgIHsKICAgICAgICAgICAgImZpZWxkbmFtZSI6IGYuZ2V0KCJmaWVsZG5hbWUiKSwKICAgICAgICAgICAgImZpZWxkdHlwZSI6IGYuZ2V0KCJmaWVsZHR5cGUiKSwKICAgICAgICAgICAgImxhYmVsIjogZi5nZXQoImxhYmVsIiksCiAgICAgICAgICAgICJvcHRpb25zIjogZi5nZXQoIm9wdGlvbnMiKSwKICAgICAgICAgICAgInJlcWQiOiBib29sKGYuZ2V0KCJyZXFkIikpLAogICAgICAgICAgICAiaW5fbGlzdF92aWV3IjogYm9vbChmLmdldCgiaW5fbGlzdF92aWV3IikpLAogICAgICAgIH0KICAgICAgICBmb3IgZiBpbiBkYXRhLmdldCgiZmllbGRzIiwgW10pCiAgICAgICAgaWYgZi5nZXQoImZpZWxkbmFtZSIpCiAgICBdCgogICAgcmV0dXJuIHsKICAgICAgICAidHlwZSI6ICJkb2N0eXBlIiwKICAgICAgICAibmFtZSI6IGRhdGEuZ2V0KCJuYW1lIiksCiAgICAgICAgIm1vZHVsZSI6IGRhdGEuZ2V0KCJtb2R1bGUiKSwKICAgICAgICAiYXBwIjoganNvbl9wYXRoLnBhcnRzW2pzb25fcGF0aC5wYXJ0cy5pbmRleCgiYXBwcyIpICsgMV0sCiAgICAgICAgImlzX3N1Ym1pdHRhYmxlIjogYm9vbChkYXRhLmdldCgiaXNfc3VibWl0dGFibGUiKSksCiAgICAgICAgImlzX2NoaWxkX3RhYmxlIjogYm9vbChkYXRhLmdldCgiaXN0YWJsZSIpKSwKICAgICAgICAidHJhY2tfY2hhbmdlcyI6IGJvb2woZGF0YS5nZXQoInRyYWNrX2NoYW5nZXMiKSksCiAgICAgICAgImZpZWxkcyI6IGZpZWxkcywKICAgICAgICAicGVybWlzc2lvbnMiOiBbCiAgICAgICAgICAgIHsicm9sZSI6IHAuZ2V0KCJyb2xlIiksICJyZWFkIjogcC5nZXQoInJlYWQiKSwgIndyaXRlIjogcC5nZXQoIndyaXRlIil9CiAgICAgICAgICAgIGZvciBwIGluIGRhdGEuZ2V0KCJwZXJtaXNzaW9ucyIsIFtdKQogICAgICAgIF0sCiAgICAgICAgInNvdXJjZSI6IHN0cihqc29uX3BhdGgucmVsYXRpdmVfdG8oQkVOQ0hfUEFUSCkpLAogICAgfQoKCmRlZiBleHRyYWN0X2NvbnRyb2xsZXIocHlfcGF0aDogUGF0aCkgLT4gZGljdCB8IE5vbmU6CiAgICB0cnk6CiAgICAgICAgc291cmNlID0gcHlfcGF0aC5yZWFkX3RleHQoKQogICAgICAgIHRyZWUgPSBhc3QucGFyc2Uoc291cmNlKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gTm9uZQoKICAgIGFwcCA9IHB5X3BhdGgucGFydHNbcHlfcGF0aC5wYXJ0cy5pbmRleCgiYXBwcyIpICsgMV0KICAgIG1ldGhvZHMgPSBbXQogICAgY29udHJvbGxlcl9uYW1lID0gTm9uZQoKICAgIGZvciBub2RlIGluIGFzdC53YWxrKHRyZWUpOgogICAgICAgIGlmIGlzaW5zdGFuY2Uobm9kZSwgYXN0LkNsYXNzRGVmKToKICAgICAgICAgICAgY29udHJvbGxlcl9uYW1lID0gbm9kZS5uYW1lCiAgICAgICAgICAgIGZvciBpdGVtIGluIG5vZGUuYm9keToKICAgICAgICAgICAgICAgIGlmIGlzaW5zdGFuY2UoaXRlbSwgYXN0LkZ1bmN0aW9uRGVmKToKICAgICAgICAgICAgICAgICAgICBkb2NzdHJpbmcgPSBhc3QuZ2V0X2RvY3N0cmluZyhpdGVtKSBvciAiIgogICAgICAgICAgICAgICAgICAgIGFyZ3MgPSBbYS5hcmcgZm9yIGEgaW4gaXRlbS5hcmdzLmFyZ3MgaWYgYS5hcmcgIT0gInNlbGYiXQogICAgICAgICAgICAgICAgICAgIG1ldGhvZHMuYXBwZW5kKHsKICAgICAgICAgICAgICAgICAgICAgICAgIm5hbWUiOiBpdGVtLm5hbWUsCiAgICAgICAgICAgICAgICAgICAgICAgICJhcmdzIjogYXJncywKICAgICAgICAgICAgICAgICAgICAgICAgImRvY3N0cmluZyI6IGRvY3N0cmluZ1s6MjAwXSBpZiBkb2NzdHJpbmcgZWxzZSBOb25lLAogICAgICAgICAgICAgICAgICAgIH0pCgogICAgaWYgbm90IGNvbnRyb2xsZXJfbmFtZToKICAgICAgICByZXR1cm4gTm9uZQoKICAgIHJldHVybiB7CiAgICAgICAgInR5cGUiOiAiY29udHJvbGxlciIsCiAgICAgICAgImFwcCI6IGFwcCwKICAgICAgICAiY29udHJvbGxlciI6IGNvbnRyb2xsZXJfbmFtZSwKICAgICAgICAibWV0aG9kcyI6IG1ldGhvZHMsCiAgICAgICAgInNvdXJjZSI6IHN0cihweV9wYXRoLnJlbGF0aXZlX3RvKEJFTkNIX1BBVEgpKSwKICAgIH0KCgpkZWYgZXh0cmFjdF93aGl0ZWxpc3RlZF9hcGlzKHB5X3BhdGg6IFBhdGgpIC0+IGxpc3RbZGljdF06CiAgICB0cnk6CiAgICAgICAgc291cmNlID0gcHlfcGF0aC5yZWFkX3RleHQoKQogICAgICAgIHRyZWUgPSBhc3QucGFyc2Uoc291cmNlKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gW10KCiAgICBhcHAgPSBweV9wYXRoLnBhcnRzW3B5X3BhdGgucGFydHMuaW5kZXgoImFwcHMiKSArIDFdCiAgICBhcGlzID0gW10KCiAgICBmb3Igbm9kZSBpbiBhc3Qud2Fsayh0cmVlKToKICAgICAgICBpZiBub3QgaXNpbnN0YW5jZShub2RlLCAoYXN0LkZ1bmN0aW9uRGVmLCBhc3QuQXN5bmNGdW5jdGlvbkRlZikpOgogICAgICAgICAgICBjb250aW51ZQoKICAgICAgICBkZWNvcmF0b3JzID0gWwogICAgICAgICAgICBhc3QudW5wYXJzZShkKSBpZiBoYXNhdHRyKGFzdCwgInVucGFyc2UiKSBlbHNlIGdldGF0dHIoZCwgImlkIiwgIiIpCiAgICAgICAgICAgIGZvciBkIGluIG5vZGUuZGVjb3JhdG9yX2xpc3QKICAgICAgICBdCiAgICAgICAgaXNfd2hpdGVsaXN0ZWQgPSBhbnkoIndoaXRlbGlzdCIgaW4gZCBmb3IgZCBpbiBkZWNvcmF0b3JzKQogICAgICAgIGlmIG5vdCBpc193aGl0ZWxpc3RlZDoKICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgYXJncyA9IFthLmFyZyBmb3IgYSBpbiBub2RlLmFyZ3MuYXJnc10KICAgICAgICBkb2NzdHJpbmcgPSBhc3QuZ2V0X2RvY3N0cmluZyhub2RlKSBvciAiIgoKICAgICAgICBhcGlzLmFwcGVuZCh7CiAgICAgICAgICAgICJ0eXBlIjogImFwaSIsCiAgICAgICAgICAgICJhcHAiOiBhcHAsCiAgICAgICAgICAgICJmdW5jdGlvbiI6IG5vZGUubmFtZSwKICAgICAgICAgICAgImFyZ3MiOiBhcmdzLAogICAgICAgICAgICAiZG9jc3RyaW5nIjogZG9jc3RyaW5nWzozMDBdIGlmIGRvY3N0cmluZyBlbHNlIE5vbmUsCiAgICAgICAgICAgICJkZWNvcmF0b3JzIjogZGVjb3JhdG9ycywKICAgICAgICAgICAgInNvdXJjZSI6IHN0cihweV9wYXRoLnJlbGF0aXZlX3RvKEJFTkNIX1BBVEgpKSwKICAgICAgICB9KQoKICAgIHJldHVybiBhcGlzCgoKZGVmIGV4dHJhY3RfaG9va3MoaG9va3NfcGF0aDogUGF0aCkgLT4gZGljdCB8IE5vbmU6CiAgICB0cnk6CiAgICAgICAgc291cmNlID0gaG9va3NfcGF0aC5yZWFkX3RleHQoKQogICAgICAgIHRyZWUgPSBhc3QucGFyc2Uoc291cmNlKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gTm9uZQoKICAgIGFwcCA9IGhvb2tzX3BhdGgucGFydHNbaG9va3NfcGF0aC5wYXJ0cy5pbmRleCgiYXBwcyIpICsgMV0KICAgIGhvb2tzID0ge30KCiAgICBmb3Igbm9kZSBpbiBhc3Qud2Fsayh0cmVlKToKICAgICAgICBpZiBpc2luc3RhbmNlKG5vZGUsIGFzdC5Bc3NpZ24pOgogICAgICAgICAgICBmb3IgdGFyZ2V0IGluIG5vZGUudGFyZ2V0czoKICAgICAgICAgICAgICAgIGlmIGlzaW5zdGFuY2UodGFyZ2V0LCBhc3QuTmFtZSk6CiAgICAgICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgICAgICBob29rc1t0YXJnZXQuaWRdID0gYXN0LmxpdGVyYWxfZXZhbChub2RlLnZhbHVlKQogICAgICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgICAgICAgICAgICAgIGhvb2tzW3RhcmdldC5pZF0gPSAiX19jb21wbGV4X18iCgogICAgcmV0dXJuIHsKICAgICAgICAidHlwZSI6ICJob29rcyIsCiAgICAgICAgImFwcCI6IGFwcCwKICAgICAgICAiaG9va3MiOiBob29rcywKICAgICAgICAic291cmNlIjogc3RyKGhvb2tzX3BhdGgucmVsYXRpdmVfdG8oQkVOQ0hfUEFUSCkpLAogICAgfQoKCmRlZiBnZW5lcmF0ZV9jb3JwdXMoYXBwczogbGlzdFtzdHJdLCBvdXRwdXQ6IFBhdGgpOgogICAgcmVjb3JkcyA9IFtdCiAgICBzdGF0cyA9IHsiZG9jdHlwZXMiOiAwLCAiY29udHJvbGxlcnMiOiAwLCAiYXBpcyI6IDAsICJob29rcyI6IDAsICJza2lwcGVkIjogMH0KCiAgICBmb3IgYXBwX25hbWUgaW4gYXBwczoKICAgICAgICBhcHBfcGF0aCA9IEFQUFNfUEFUSCAvIGFwcF9uYW1lCiAgICAgICAgaWYgbm90IGFwcF9wYXRoLmV4aXN0cygpOgogICAgICAgICAgICBwcmludChmIiAgW3NraXBdIHthcHBfbmFtZX0g4oCUIG5vdCBmb3VuZCIpCiAgICAgICAgICAgIGNvbnRpbnVlCgogICAgICAgIHByaW50KGYiICBQcm9jZXNzaW5nIHthcHBfbmFtZX0uLi4iKQoKICAgICAgICAjIERvY1R5cGUgc2NoZW1hcwogICAgICAgIGZvciBqc29uX3BhdGggaW4gc29ydGVkKGFwcF9wYXRoLnJnbG9iKCIqLmpzb24iKSk6CiAgICAgICAgICAgIGlmICIvZG9jdHlwZS8iIG5vdCBpbiBzdHIoanNvbl9wYXRoKToKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIHJlY29yZCA9IGV4dHJhY3RfZG9jdHlwZShqc29uX3BhdGgpCiAgICAgICAgICAgIGlmIHJlY29yZDoKICAgICAgICAgICAgICAgIHJlY29yZHMuYXBwZW5kKHJlY29yZCkKICAgICAgICAgICAgICAgIHN0YXRzWyJkb2N0eXBlcyJdICs9IDEKCiAgICAgICAgIyBDb250cm9sbGVycwogICAgICAgIGZvciBweV9wYXRoIGluIHNvcnRlZChhcHBfcGF0aC5yZ2xvYigiKi5weSIpKToKICAgICAgICAgICAgaWYgIi9kb2N0eXBlLyIgbm90IGluIHN0cihweV9wYXRoKToKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIHJlY29yZCA9IGV4dHJhY3RfY29udHJvbGxlcihweV9wYXRoKQogICAgICAgICAgICBpZiByZWNvcmQ6CiAgICAgICAgICAgICAgICByZWNvcmRzLmFwcGVuZChyZWNvcmQpCiAgICAgICAgICAgICAgICBzdGF0c1siY29udHJvbGxlcnMiXSArPSAxCgogICAgICAgICMgV2hpdGVsaXN0ZWQgQVBJcyAoYWxsIHB5dGhvbiBmaWxlcykKICAgICAgICBmb3IgcHlfcGF0aCBpbiBzb3J0ZWQoYXBwX3BhdGgucmdsb2IoIioucHkiKSk6CiAgICAgICAgICAgIGFwaXMgPSBleHRyYWN0X3doaXRlbGlzdGVkX2FwaXMocHlfcGF0aCkKICAgICAgICAgICAgcmVjb3Jkcy5leHRlbmQoYXBpcykKICAgICAgICAgICAgc3RhdHNbImFwaXMiXSArPSBsZW4oYXBpcykKCiAgICAgICAgIyBIb29rcwogICAgICAgIGhvb2tzX3BhdGggPSBhcHBfcGF0aCAvIGFwcF9uYW1lIC8gImhvb2tzLnB5IgogICAgICAgIGlmIGhvb2tzX3BhdGguZXhpc3RzKCk6CiAgICAgICAgICAgIHJlY29yZCA9IGV4dHJhY3RfaG9va3MoaG9va3NfcGF0aCkKICAgICAgICAgICAgaWYgcmVjb3JkOgogICAgICAgICAgICAgICAgcmVjb3Jkcy5hcHBlbmQocmVjb3JkKQogICAgICAgICAgICAgICAgc3RhdHNbImhvb2tzIl0gKz0gMQoKICAgIHdpdGggb3V0cHV0Lm9wZW4oInciKSBhcyBmOgogICAgICAgIGZvciByZWNvcmQgaW4gcmVjb3JkczoKICAgICAgICAgICAgZi53cml0ZShqc29uLmR1bXBzKHJlY29yZCwgZGVmYXVsdD1zdHIpICsgIlxuIikKCiAgICByZXR1cm4gc3RhdHMsIGxlbihyZWNvcmRzKQoKCmRlZiBtYWluKCk6CiAgICBwYXJzZXIgPSBhcmdwYXJzZS5Bcmd1bWVudFBhcnNlcihkZXNjcmlwdGlvbj0iR2VuZXJhdGUgY29ycHVzLmpzb25sIGZvciBGcmFwcGUgYXBwcyIpCiAgICBwYXJzZXIuYWRkX2FyZ3VtZW50KCItLWFwcHMiLCBuYXJncz0iKyIsIGRlZmF1bHQ9Q1VTVE9NX0FQUFMsIGhlbHA9IkFwcCBuYW1lcyB0byBpbmNsdWRlIikKICAgIHBhcnNlci5hZGRfYXJndW1lbnQoIi0tb3V0cHV0IiwgZGVmYXVsdD0iY29ycHVzLmpzb25sIiwgaGVscD0iT3V0cHV0IGZpbGUgcGF0aCIpCiAgICBhcmdzID0gcGFyc2VyLnBhcnNlX2FyZ3MoKQoKICAgIG91dHB1dCA9IFBhdGgoYXJncy5vdXRwdXQpCiAgICBwcmludChmIkdlbmVyYXRpbmcgY29ycHVzIGZyb206IHsnLCAnLmpvaW4oYXJncy5hcHBzKX0iKQogICAgcHJpbnQoZiJPdXRwdXQ6IHtvdXRwdXR9XG4iKQoKICAgIHN0YXRzLCB0b3RhbCA9IGdlbmVyYXRlX2NvcnB1cyhhcmdzLmFwcHMsIG91dHB1dCkKCiAgICBwcmludChmIlxuRG9uZS4ge3RvdGFsfSByZWNvcmRzIHdyaXR0ZW4gdG8ge291dHB1dH0iKQogICAgcHJpbnQoZiIgIERvY1R5cGVzOiAgICB7c3RhdHNbJ2RvY3R5cGVzJ119IikKICAgIHByaW50KGYiICBDb250cm9sbGVyczoge3N0YXRzWydjb250cm9sbGVycyddfSIpCiAgICBwcmludChmIiAgQVBJczogICAgICAgIHtzdGF0c1snYXBpcyddfSIpCiAgICBwcmludChmIiAgSG9va3M6ICAgICAgIHtzdGF0c1snaG9va3MnXX0iKQogICAgc2l6ZV9rYiA9IG91dHB1dC5zdGF0KCkuc3Rfc2l6ZSAvIDEwMjQKICAgIHByaW50KGYiICBGaWxlIHNpemU6ICAge3NpemVfa2I6LjFmfSBLQiIpCgoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIG1haW4oKQo=" | base64 -d > "$SKILL_DIR/generate_corpus.py"

# search_corpus.py
echo "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIKU2VhcmNoIGNvcnB1cy5qc29ubCBhbmQgcmV0dXJuIG9ubHkgcmVsZXZhbnQgcmVjb3JkcyBmb3IgYSB0YXNrLgpLZWVwcyBQaGFzZSAxIGNvbnRleHQgc21hbGwgaW5zdGVhZCBvZiBsb2FkaW5nIGFsbCAxLDc2MSByZWNvcmRzLgoKVXNhZ2U6CiAgICBweXRob24zIHNlYXJjaF9jb3JwdXMucHkgImFkZCBmZWUgY2FsY3VsYXRpb24gdG8gZXNjcm93IHNldHRsZW1lbnQiCiAgICBweXRob24zIHNlYXJjaF9jb3JwdXMucHkgInBheW91dCBhcHByb3ZhbCB3b3JrZmxvdyIgLS1hcHAgcDJwX2VzY3JvdwogICAgcHl0aG9uMyBzZWFyY2hfY29ycHVzLnB5ICJ3aGl0ZWxpc3RlZCBhcGlzIGZvciBiYXRjaCIgLS10eXBlIGFwaQogICAgcHl0aG9uMyBzZWFyY2hfY29ycHVzLnB5ICJlc2Nyb3cgbWVyY2hhbnQiIC0tdG9wIDEwCiIiIgoKaW1wb3J0IGpzb24KaW1wb3J0IG9zCmltcG9ydCByZQppbXBvcnQgYXJncGFyc2UKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpkZWYgX2ZpbmRfY29ycHVzKCkgLT4gUGF0aDoKICAgICIiIkZpbmQgY29ycHVzLmpzb25sIOKAlCBjaGVjayBDV0QsIHRoZW4gd2FsayB1cCwgdGhlbiBGUkFQUEVfQkVOQ0hfUEFUSCBlbnYuIiIiCiAgICBlbnZfcGF0aCA9IG9zLmVudmlyb24uZ2V0KCJDT1JQVVNfUEFUSCIpCiAgICBpZiBlbnZfcGF0aDoKICAgICAgICByZXR1cm4gUGF0aChlbnZfcGF0aCkKICAgIGZvciBwYXRoIGluIFtQYXRoLmN3ZCgpLCAqUGF0aC5jd2QoKS5wYXJlbnRzXToKICAgICAgICBjYW5kaWRhdGUgPSBwYXRoIC8gImNvcnB1cy5qc29ubCIKICAgICAgICBpZiBjYW5kaWRhdGUuZXhpc3RzKCk6CiAgICAgICAgICAgIHJldHVybiBjYW5kaWRhdGUKICAgIHJldHVybiBQYXRoLmN3ZCgpIC8gImNvcnB1cy5qc29ubCIKCkNPUlBVU19QQVRIID0gX2ZpbmRfY29ycHVzKCkKClNUT1BfV09SRFMgPSB7CiAgICAiYSIsICJhbiIsICJ0aGUiLCAiYW5kIiwgIm9yIiwgImZvciIsICJ0byIsICJpbiIsICJvbiIsICJvZiIsCiAgICAiYWRkIiwgImNyZWF0ZSIsICJidWlsZCIsICJtYWtlIiwgIm5ldyIsICJnZXQiLCAic2V0IiwgInVwZGF0ZSIsCiAgICAid2l0aCIsICJ0aGlzIiwgInRoYXQiLCAiZnJvbSIsICJpbnRvIiwgImlzIiwgIml0IiwgImJlIiwgImFzIiwKfQoKCmRlZiB0b2tlbml6ZSh0ZXh0OiBzdHIpIC0+IGxpc3Rbc3RyXToKICAgIHRva2VucyA9IHJlLmZpbmRhbGwociJbYS16MC05XSsiLCB0ZXh0Lmxvd2VyKCkpCiAgICByZXR1cm4gW3QgZm9yIHQgaW4gdG9rZW5zIGlmIHQgbm90IGluIFNUT1BfV09SRFMgYW5kIGxlbih0KSA+IDJdCgoKZGVmIHJlY29yZF90ZXh0KHJlY29yZDogZGljdCkgLT4gc3RyOgogICAgIiIiRmxhdHRlbiBhIHJlY29yZCBpbnRvIHNlYXJjaGFibGUgdGV4dC4iIiIKICAgIHBhcnRzID0gWwogICAgICAgIHJlY29yZC5nZXQoIm5hbWUiLCAiIiksCiAgICAgICAgcmVjb3JkLmdldCgibW9kdWxlIiwgIiIpLAogICAgICAgIHJlY29yZC5nZXQoImFwcCIsICIiKSwKICAgICAgICByZWNvcmQuZ2V0KCJjb250cm9sbGVyIiwgIiIpLAogICAgICAgIHJlY29yZC5nZXQoImZ1bmN0aW9uIiwgIiIpLAogICAgICAgIHJlY29yZC5nZXQoImRvY3N0cmluZyIsICIiKSBvciAiIiwKICAgIF0KCiAgICBpZiByZWNvcmQuZ2V0KCJ0eXBlIikgPT0gImRvY3R5cGUiOgogICAgICAgIGZvciBmIGluIHJlY29yZC5nZXQoImZpZWxkcyIsIFtdKToKICAgICAgICAgICAgcGFydHMgKz0gW2YuZ2V0KCJmaWVsZG5hbWUiLCAiIiksIGYuZ2V0KCJsYWJlbCIsICIiKSBvciAiIiwgZi5nZXQoIm9wdGlvbnMiLCAiIikgb3IgIiJdCgogICAgaWYgcmVjb3JkLmdldCgidHlwZSIpID09ICJjb250cm9sbGVyIjoKICAgICAgICBmb3IgbSBpbiByZWNvcmQuZ2V0KCJtZXRob2RzIiwgW10pOgogICAgICAgICAgICBwYXJ0cyArPSBbbS5nZXQoIm5hbWUiLCAiIiksIG0uZ2V0KCJkb2NzdHJpbmciLCAiIikgb3IgIiJdCgogICAgaWYgcmVjb3JkLmdldCgidHlwZSIpID09ICJhcGkiOgogICAgICAgIHBhcnRzICs9IHJlY29yZC5nZXQoImFyZ3MiLCBbXSkKCiAgICBpZiByZWNvcmQuZ2V0KCJ0eXBlIikgPT0gImhvb2tzIjoKICAgICAgICBwYXJ0cyArPSBsaXN0KHJlY29yZC5nZXQoImhvb2tzIiwge30pLmtleXMoKSkKCiAgICByZXR1cm4gIiAiLmpvaW4oc3RyKHApIGZvciBwIGluIHBhcnRzIGlmIHApCgoKZGVmIHNjb3JlKHJlY29yZDogZGljdCwgdG9rZW5zOiBsaXN0W3N0cl0pIC0+IGludDoKICAgIHRleHQgPSByZWNvcmRfdGV4dChyZWNvcmQpLmxvd2VyKCkKICAgIHRleHRfdG9rZW5zID0gdG9rZW5pemUodGV4dCkKCiAgICBzID0gMAogICAgbmFtZSA9IChyZWNvcmQuZ2V0KCJuYW1lIikgb3IgcmVjb3JkLmdldCgiZnVuY3Rpb24iKSBvciByZWNvcmQuZ2V0KCJjb250cm9sbGVyIikgb3IgIiIpLmxvd2VyKCkKCiAgICBmb3IgdG9rZW4gaW4gdG9rZW5zOgogICAgICAgIGlmIHRva2VuIGluIG5hbWU6CiAgICAgICAgICAgIHMgKz0gNSAgICAgICAgICAjIHN0cm9uZyBzaWduYWw6IHF1ZXJ5IHRva2VuIGluIHJlY29yZCBuYW1lCiAgICAgICAgZWxpZiB0b2tlbiBpbiB0ZXh0OgogICAgICAgICAgICBzICs9IDEgICAgICAgICAgIyB3ZWFrIHNpZ25hbDogYW55d2hlcmUgaW4gcmVjb3JkCgogICAgICAgICMgYm9udXM6IGV4YWN0IG11bHRpLXdvcmQgbWF0Y2ggaW4gbmFtZQogICAgICAgIGlmIGxlbih0b2tlbnMpID4gMToKICAgICAgICAgICAgcGhyYXNlID0gIl8iLmpvaW4odG9rZW5zKQogICAgICAgICAgICBpZiBwaHJhc2UgaW4gbmFtZS5yZXBsYWNlKCIgIiwgIl8iKToKICAgICAgICAgICAgICAgIHMgKz0gMTAKCiAgICByZXR1cm4gcwoKCmRlZiBzZWFyY2gocXVlcnk6IHN0ciwgYXBwOiBzdHIgfCBOb25lLCByZWNvcmRfdHlwZTogc3RyIHwgTm9uZSwgdG9wOiBpbnQpIC0+IGxpc3RbZGljdF06CiAgICB0b2tlbnMgPSB0b2tlbml6ZShxdWVyeSkKICAgIGlmIG5vdCB0b2tlbnM6CiAgICAgICAgcmV0dXJuIFtdCgogICAgcmVzdWx0cyA9IFtdCiAgICB3aXRoIENPUlBVU19QQVRILm9wZW4oKSBhcyBmOgogICAgICAgIGZvciBsaW5lIGluIGY6CiAgICAgICAgICAgIGxpbmUgPSBsaW5lLnN0cmlwKCkKICAgICAgICAgICAgaWYgbm90IGxpbmU6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICByZWNvcmQgPSBqc29uLmxvYWRzKGxpbmUpCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgICAgICBjb250aW51ZQoKICAgICAgICAgICAgaWYgYXBwIGFuZCByZWNvcmQuZ2V0KCJhcHAiKSAhPSBhcHA6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICBpZiByZWNvcmRfdHlwZSBhbmQgcmVjb3JkLmdldCgidHlwZSIpICE9IHJlY29yZF90eXBlOgogICAgICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgICAgIHMgPSBzY29yZShyZWNvcmQsIHRva2VucykKICAgICAgICAgICAgaWYgcyA+IDA6CiAgICAgICAgICAgICAgICByZXN1bHRzLmFwcGVuZCgocywgcmVjb3JkKSkKCiAgICByZXN1bHRzLnNvcnQoa2V5PWxhbWJkYSB4OiB4WzBdLCByZXZlcnNlPVRydWUpCiAgICByZXR1cm4gW3IgZm9yIF8sIHIgaW4gcmVzdWx0c1s6dG9wXV0KCgpkZWYgZm9ybWF0X3JlY29yZChyZWNvcmQ6IGRpY3QpIC0+IHN0cjoKICAgIHQgPSByZWNvcmQuZ2V0KCJ0eXBlIikKICAgIGxpbmVzID0gW10KCiAgICBpZiB0ID09ICJkb2N0eXBlIjoKICAgICAgICBsaW5lcy5hcHBlbmQoZiJbZG9jdHlwZV0ge3JlY29yZFsnbmFtZSddfSDigJQgYXBwOntyZWNvcmRbJ2FwcCddfSBtb2R1bGU6e3JlY29yZFsnbW9kdWxlJ119IikKICAgICAgICBsaW5lcy5hcHBlbmQoZiIgIHN1Ym1pdHRhYmxlOntyZWNvcmRbJ2lzX3N1Ym1pdHRhYmxlJ119IGNoaWxkX3RhYmxlOntyZWNvcmRbJ2lzX2NoaWxkX3RhYmxlJ119IikKICAgICAgICBmb3IgZiBpbiByZWNvcmQuZ2V0KCJmaWVsZHMiLCBbXSk6CiAgICAgICAgICAgIGlmIGYuZ2V0KCJmaWVsZG5hbWUiKToKICAgICAgICAgICAgICAgIG9wdHMgPSBmIiDihpIge2ZbJ29wdGlvbnMnXX0iIGlmIGYuZ2V0KCJvcHRpb25zIikgZWxzZSAiIgogICAgICAgICAgICAgICAgcmVxID0gIiAqIiBpZiBmLmdldCgicmVxZCIpIGVsc2UgIiIKICAgICAgICAgICAgICAgIGxpbmVzLmFwcGVuZChmIiAge2ZbJ2ZpZWxkbmFtZSddfSAoe2ZbJ2ZpZWxkdHlwZSddfSl7b3B0c317cmVxfSIpCgogICAgZWxpZiB0ID09ICJjb250cm9sbGVyIjoKICAgICAgICBsaW5lcy5hcHBlbmQoZiJbY29udHJvbGxlcl0ge3JlY29yZFsnY29udHJvbGxlciddfSDigJQge3JlY29yZFsnc291cmNlJ119IikKICAgICAgICBmb3IgbSBpbiByZWNvcmQuZ2V0KCJtZXRob2RzIiwgW10pOgogICAgICAgICAgICBhcmdzID0gIiwgIi5qb2luKG0uZ2V0KCJhcmdzIiwgW10pKQogICAgICAgICAgICBkb2MgPSBmIiDigJQge21bJ2RvY3N0cmluZyddWzo4MF19IiBpZiBtLmdldCgiZG9jc3RyaW5nIikgZWxzZSAiIgogICAgICAgICAgICBsaW5lcy5hcHBlbmQoZiIgIGRlZiB7bVsnbmFtZSddfSh7YXJnc30pe2RvY30iKQoKICAgIGVsaWYgdCA9PSAiYXBpIjoKICAgICAgICBhcmdzID0gIiwgIi5qb2luKHJlY29yZC5nZXQoImFyZ3MiLCBbXSkpCiAgICAgICAgbGluZXMuYXBwZW5kKGYiW2FwaV0ge3JlY29yZFsnZnVuY3Rpb24nXX0oe2FyZ3N9KSDigJQge3JlY29yZFsnc291cmNlJ119IikKICAgICAgICBpZiByZWNvcmQuZ2V0KCJkb2NzdHJpbmciKToKICAgICAgICAgICAgbGluZXMuYXBwZW5kKGYiICB7cmVjb3JkWydkb2NzdHJpbmcnXVs6MTIwXX0iKQoKICAgIGVsaWYgdCA9PSAiaG9va3MiOgogICAgICAgIGxpbmVzLmFwcGVuZChmIltob29rc10gYXBwOntyZWNvcmRbJ2FwcCddfSIpCiAgICAgICAgZm9yIGssIHYgaW4gcmVjb3JkLmdldCgiaG9va3MiLCB7fSkuaXRlbXMoKToKICAgICAgICAgICAgbGluZXMuYXBwZW5kKGYiICB7a306IHtzdHIodilbOjgwXX0iKQoKICAgIHJldHVybiAiXG4iLmpvaW4obGluZXMpCgoKZGVmIG1haW4oKToKICAgIHBhcnNlciA9IGFyZ3BhcnNlLkFyZ3VtZW50UGFyc2VyKGRlc2NyaXB0aW9uPSJTZWFyY2ggY29ycHVzLmpzb25sIGZvciByZWxldmFudCBjb250ZXh0IikKICAgIHBhcnNlci5hZGRfYXJndW1lbnQoInF1ZXJ5IiwgaGVscD0iVGFzayBkZXNjcmlwdGlvbiBvciBrZXl3b3JkcyIpCiAgICBwYXJzZXIuYWRkX2FyZ3VtZW50KCItLWFwcCIsIGhlbHA9IkZpbHRlciBieSBhcHAgbmFtZSAoZS5nLiBwMnBfZXNjcm93KSIpCiAgICBwYXJzZXIuYWRkX2FyZ3VtZW50KCItLXR5cGUiLCBkZXN0PSJyZWNvcmRfdHlwZSIsIGNob2ljZXM9WyJkb2N0eXBlIiwgImNvbnRyb2xsZXIiLCAiYXBpIiwgImhvb2tzIl0sCiAgICAgICAgICAgICAgICAgICAgICAgIGhlbHA9IkZpbHRlciBieSByZWNvcmQgdHlwZSIpCiAgICBwYXJzZXIuYWRkX2FyZ3VtZW50KCItLXRvcCIsIHR5cGU9aW50LCBkZWZhdWx0PTIwLCBoZWxwPSJNYXggcmVjb3JkcyB0byByZXR1cm4gKGRlZmF1bHQ6IDIwKSIpCiAgICBwYXJzZXIuYWRkX2FyZ3VtZW50KCItLWpzb24iLCBhY3Rpb249InN0b3JlX3RydWUiLCBoZWxwPSJPdXRwdXQgcmF3IEpTT04gbGluZXMgaW5zdGVhZCBvZiBmb3JtYXR0ZWQgdGV4dCIpCiAgICBhcmdzID0gcGFyc2VyLnBhcnNlX2FyZ3MoKQoKICAgIGlmIG5vdCBDT1JQVVNfUEFUSC5leGlzdHMoKToKICAgICAgICBwcmludChmIkVSUk9SOiBjb3JwdXMuanNvbmwgbm90IGZvdW5kIGF0IHtDT1JQVVNfUEFUSH0iKQogICAgICAgIHByaW50KCJSdW46IHB5dGhvbjMgZ2VuZXJhdGVfY29ycHVzLnB5IikKICAgICAgICByZXR1cm4KCiAgICByZXN1bHRzID0gc2VhcmNoKGFyZ3MucXVlcnksIGFyZ3MuYXBwLCBhcmdzLnJlY29yZF90eXBlLCBhcmdzLnRvcCkKCiAgICBpZiBub3QgcmVzdWx0czoKICAgICAgICBwcmludChmIk5vIHJlc3VsdHMgZm9yOiB7YXJncy5xdWVyeX0iKQogICAgICAgIHJldHVybgoKICAgIHByaW50KGYiIyBDb3JwdXMgc2VhcmNoOiAne2FyZ3MucXVlcnl9JyDigJQge2xlbihyZXN1bHRzKX0gcmVzdWx0c1xuIikKCiAgICBpZiBhcmdzLmpzb246CiAgICAgICAgZm9yIHIgaW4gcmVzdWx0czoKICAgICAgICAgICAgcHJpbnQoanNvbi5kdW1wcyhyKSkKICAgIGVsc2U6CiAgICAgICAgZm9yIHIgaW4gcmVzdWx0czoKICAgICAgICAgICAgcHJpbnQoZm9ybWF0X3JlY29yZChyKSkKICAgICAgICAgICAgcHJpbnQoKQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBtYWluKCkK" | base64 -d > "$SKILL_DIR/search_corpus.py"

# install.sh
cat > "$SKILL_DIR/install.sh" << 'INSTALLEOF'
#!/bin/bash
# Install the /dev skill and corpus tools into a new container.
#
# Usage:
#   bash install.sh                  # install globally + set up current project
#   bash install.sh --global-only    # only install the Claude skill, skip project hooks

set -e

SKILL_DIR="$HOME/.claude/skills/dev"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GLOBAL_ONLY=false

for arg in "$@"; do
  [[ "$arg" == "--global-only" ]] && GLOBAL_ONLY=true
done

echo "=== Installing /dev skill ==="

# 1. Copy skill files to ~/.claude/skills/dev/
mkdir -p "$SKILL_DIR"
cp "$SCRIPT_DIR/SKILL.md"             "$SKILL_DIR/SKILL.md"
cp "$SCRIPT_DIR/generate_corpus.py"   "$SKILL_DIR/generate_corpus.py"
cp "$SCRIPT_DIR/search_corpus.py"     "$SKILL_DIR/search_corpus.py"
cp "$SCRIPT_DIR/install.sh"           "$SKILL_DIR/install.sh"
echo "  [ok] Skill installed at $SKILL_DIR"

if $GLOBAL_ONLY; then
  echo ""
  echo "Done (global only). Run without --global-only inside a project to set up hooks."
  exit 0
fi

# 2. Set up project corpus tools in CWD
echo ""
echo "=== Setting up corpus in $(pwd) ==="

cp "$SKILL_DIR/generate_corpus.py" ./generate_corpus.py
cp "$SKILL_DIR/search_corpus.py"   ./search_corpus.py
echo "  [ok] generate_corpus.py and search_corpus.py copied to $(pwd)"

# 3. Generate the initial corpus
echo "  Generating corpus.jsonl..."
python3 generate_corpus.py
echo "  [ok] corpus.jsonl generated"

# 4. Set up Claude Code project hook (auto-regenerate on file edits)
mkdir -p .claude/hooks

cat > .claude/hooks/refresh_corpus.sh << 'HOOK'
#!/bin/bash
input=$(cat)
file_path=$(echo "$input" | python3 -c "
import json, sys
data = json.load(sys.stdin)
inp = data.get('tool_input', {})
print(inp.get('file_path', inp.get('path', '')))
" 2>/dev/null)

if [[ "$file_path" != *"/apps/"* ]]; then exit 0; fi
if [[ "$file_path" != *.py && "$file_path" != *.json ]]; then exit 0; fi

echo "[corpus] Change in $file_path — regenerating corpus.jsonl..." >&2
python3 "$(dirname "$0")/../../generate_corpus.py" >&2
echo "[corpus] Done." >&2
HOOK

chmod +x .claude/hooks/refresh_corpus.sh
echo "  [ok] PostToolUse hook installed at .claude/hooks/refresh_corpus.sh"

# 5. Create .claude/settings.json if it doesn't exist
if [ ! -f .claude/settings.json ]; then
  cat > .claude/settings.json << 'JSON'
{
  "hooks": {
    "PostToolUse": [
      {
        "matcher": "Edit|Write",
        "hooks": [
          {
            "type": "command",
            "command": "bash .claude/hooks/refresh_corpus.sh"
          }
        ]
      }
    ]
  }
}
JSON
  echo "  [ok] .claude/settings.json created"
else
  echo "  [skip] .claude/settings.json already exists — add hook manually if needed"
fi

echo ""
echo "=== All done ==="
echo "  /dev skill is ready. Type /dev <task description> to start."

INSTALLEOF

chmod +x "$SKILL_DIR/install.sh"
echo "[ok] Skill files installed."
echo ""
echo "Now run the project installer:"
echo "  cd <your-frappe-bench-or-project>"
echo "  bash ~/.claude/skills/dev/install.sh"
